task: cont_space_llm_num_optim
num_episodes: 200
gym_env_name: Swimmer-v5
render_mode: null
logdir: logs/swimmer_svd_test1
dim_actions: 6
dim_states: 17
max_traj_count: 1000
max_traj_length: 1000
template_dir: agent/policy/templates
llm_si_template_name: num_optim_svd.j2
llm_output_conversion_template_name: num_optim_svd.j2
llm_model_name: gpt-oss:120b
num_evaluation_episodes: 20
warmup_episodes: 20
warmup_dir: null
bias: true
optimum: 5000
search_step_size: 0.1
use_factorized_policy: true
factor_rank: 3
decomposition_type: svd
frozen_factor: null
matrix_init_mode: near_zero
enable_matrix_delta_signal: true
enable_reward_dip_reset_to_best: false
reward_dip_reset_threshold: -200.0
enable_reward_delta_reset_to_best: false
reward_delta_prev_reset_threshold: -350.0
reward_delta_best_reset_threshold: -600.0
enable_svd_phase_freezing: true
svd_phase_window: 15
svd_phase1_variance_threshold: 50.0
svd_phase2_variance_threshold: 200.0
svd_phase2_mean_drop_threshold: 100.0
enable_elite_buffer: true
elite_buffer_size: 5
reward_clip_floor: -200.0
